### ISSUE TITLE
Nextcloud 20

### ISSUE THREAD

**Issue by xXPerditorXx** [DecaTec/sharerenamer#32] opened 2021-01-28 09:01 UTC
On my share, there is no Rename Share or something...
![grafik](https://user-images.githubusercontent.com/60017046/106114421-d3e14a80-614f-11eb-9adf-819ee0586105.png)

**Comment by JonathanTreffler** [comment] 2021-01-28 09:22
This App is currently not working with the newest versions. I am working on a PR to solve this, but that will take a while.
This is a duplicate of #21.

**Closed by JonathanTreffler** 2021-01-28 09:22 UTC
