### ISSUE TITLE
it's possible to assign same share name to different items

### ISSUE THREAD

**Issue by KrullBorg** [DecaTec/sharerenamer#20] opened 2019-12-12 16:14 UTC
it's possible to assign same share name to different items

**Comment by DecaTec** [comment] 2019-12-12 22:01
You can only assign one link to one item. Renaming the second link to the first link's name will result in a message that the link is already used.

**Comment by KrullBorg** [comment] 2019-12-13 07:27
sorry, but no message here... i could do it... this is what i have in the db

id;share_type;share_with;password;uid_owner;uid_initiator;parent;item_type;item_source;item_target;file_source;file_target;permissions;stime;accepted;expiration;token;mail_send;share_name;password_by_talk;note;hide_download;label
15;3;;;admin;admin;;file;17;;17;/Nextcloud Manual.pdf;1;1576166671;0;;pippolomp4;0;;f;;0;""
14;3;;;admin;admin;;file;18;;18;/Nextcloud intro.mp4;1;1576166614;0;;pippolomp4;0;;f;;0;""

as you can see, i have 2 records with the same field token value

**Comment by DecaTec** [comment] 2019-12-13 08:48
OK, this should not be possible.

Can you please give me a step by step instruction how I can reproduce this issue?
What happens, when the shared link is used? Does it link to the pdf or mp4?

**Comment by KrullBorg** [comment] 2019-12-13 10:26
for the reproduction of the problem, nothing in particular to do: it is sufficient to assign the same name to two different files

and it opens the last created (i tried again by reversing the order)

**Comment by DecaTec** [comment] 2019-12-13 10:29
When I already have a link called "test" and I try to rename a second link to "test", I get following message (saying "Link 'test' already exists. Please chose another name").

![grafik](https://user-images.githubusercontent.com/9428899/70793434-93800b00-1d9b-11ea-8432-05146f5afcbb.png)

**Comment by KrullBorg** [comment] 2019-12-13 10:49
i'm using nextcloud latest version 17.0.1 with postgresql 11.5; sharerenamer 2.7.2

**Comment by DecaTec** [comment] 2019-12-13 10:55
OK, can reproduce this: Seems to be a problem with PostgreSQL. Will have a look at it.

**Comment by DecaTec** [comment] 2019-12-13 11:58
Fixed with 2.7.3
The update will be available very soon.

**Closed by DecaTec** 2019-12-13 11:58 UTC
Labels: bug
