### ISSUE TITLE
NextCloud (NC) 19

### ISSUE THREAD

**Issue by HieronymusCH** [DecaTec/sharerenamer#28] opened 2020-07-08 14:09 UTC
Does it work for you?
The  ShareRenamer 2.7.3 is marked as installed and active on my NextCloud 19.0.0 but it doesn't show up in the detail view of a file.

**Comment by larp-welt** [comment] 2020-07-08 14:59
Duplicate of #21

**Comment by HieronymusCH** [comment] 2020-07-08 15:27
Thanks, I close it.

**Closed** 2020-07-08 15:27 UTC

**Comment by julpec** [comment] 2020-07-10 15:36
I don't understand the link with #21 
For me, it's the same : NC19 and ShareRenamer 2.7.3 and it doesn't show up.
Is there something else to do to make it works ?

**Comment by julpec** [comment] 2020-07-10 15:38
Same with other instance of NC, v18
